export const FOODS = {
  breakfast: [
    {
      category: 'Energy-giving Foods',
      categoryBn: 'শক্তি প্রদানকারী খাবার',
      icon: '🌾',
      nutrients: ['carbs', 'energy'],
      benefit: 'Start your day with slow-release energy from whole grains to keep you going until lunch.',
      examples: [
        { name: 'Ruti (Whole Wheat Flatbread)', bnName: 'রুটি' },
        { name: 'Paratha (in moderation)', bnName: 'পরোটা (পরিমিত)' },
        { name: 'Chira (Flattened Rice)', bnName: 'চিড়া' },
        { name: 'Dalia (Wheat Porridge)', bnName: 'দলিয়া' },
        { name: 'Muri (Puffed Rice)', bnName: 'মুড়ি' },
      ],
    },
    {
      category: 'Protein-rich Foods',
      categoryBn: 'প্রোটিন সমৃদ্ধ খাবার',
      icon: '🥚',
      nutrients: ['protein', 'calcium'],
      benefit: 'Protein supports your baby\'s tissue and organ development. Include a source at every meal.',
      examples: [
        { name: 'Eggs (boiled or bhuna)', bnName: 'ডিম (সেদ্ধ বা ভুনা)' },
        { name: 'Lentil Soup (Dal)', bnName: 'ডাল' },
        { name: 'Yogurt (Doi)', bnName: 'দই' },
        { name: 'Milk', bnName: 'দুধ' },
      ],
    },
    {
      category: 'Fiber & Vitamins',
      categoryBn: 'ফাইবার ও ভিটামিন',
      icon: '🥗',
      nutrients: ['fiber', 'vitamins', 'antioxidants'],
      benefit: 'Fiber aids digestion and prevents constipation. Vitamins support overall pregnancy health.',
      examples: [
        { name: 'Mixed Vegetable Curry (Shobji)', bnName: 'সবজি তরকারি' },
        { name: 'Seasonal Fruits', bnName: 'মৌসুমী ফল' },
        { name: 'Mashed Potato (Aloo Bhorta)', bnName: 'আলু ভর্তা' },
        { name: 'Cucumber & Tomato Salad', bnName: 'শসা ও টমেটো সালাদ' },
      ],
    },
  ],
  lunch: [
    {
      category: 'Protein-rich Dishes',
      categoryBn: 'প্রোটিন সমৃদ্ধ পদ',
      icon: '🍗',
      nutrients: ['protein', 'iron', 'zinc'],
      benefit: 'A hearty protein source at lunch helps maintain your energy and supplies essential amino acids to your baby.',
      examples: [
        { name: 'Chicken Curry (Murgi Jhol)', bnName: 'মুরগি ঝোল' },
        { name: 'Beef Bhuna (3rd trimester)', bnName: 'গরুর মাংস ভুনা (তৃতীয় ত্রৈমাসিক)' },
        { name: 'Fish Curry (Pabda/Rui)', bnName: 'মাছের ঝাল (পাবদা/রুই)' },
        { name: 'Shrimp Curry (Chingri)', bnName: 'চিংড়ি কারি' },
      ],
    },
    {
      category: 'Iron-rich Foods',
      categoryBn: 'আয়রন সমৃদ্ধ খাবার',
      icon: '🩸',
      nutrients: ['iron', 'b12', 'protein'],
      benefit: 'Iron prevents anemia and supports increased blood volume during pregnancy. Pair with vitamin C for better absorption.',
      examples: [
        { name: 'Beef or Chicken Liver (occasional)', bnName: 'গরু/মুরগির কলিজা (মাঝে মাঝে)' },
        { name: 'Lentils (Dal)', bnName: 'ডাল' },
        { name: 'Dark Leafy Greens (Shobji)', bnName: 'গাঢ় সবুজ শাকসবজি' },
        { name: 'Fish Head Lentil Soup', bnName: 'মাছের মাথা দিয়ে ডাল' },
      ],
    },
    {
      category: 'Omega-3 Sources',
      categoryBn: 'ওমেগা-৩ উৎস',
      icon: '🐟',
      nutrients: ['omega3', 'vitaminD', 'calcium'],
      benefit: 'Omega-3 fatty acids are crucial for your baby\'s brain and eye development. Include 2-3 times a week.',
      examples: [
        { name: 'Hilsa Fish (Ilish — moderate)', bnName: 'ইলিশ মাছ (পরিমিত)' },
        { name: 'Pabda Fish Curry', bnName: 'পাবদা মাছের ঝাল' },
        { name: 'Shorshe Ilish', bnName: 'সরষে ইলিশ' },
        { name: 'Small Fish (Puti/Mola)', bnName: 'ছোট মাছ (পুঁটি/মলা)' },
      ],
    },
    {
      category: 'Fiber & Vegetables',
      categoryBn: 'ফাইবার ও সবজি',
      icon: '🥬',
      nutrients: ['fiber', 'vitamins', 'hydration'],
      benefit: 'Seasonal vegetables provide essential vitamins and fiber to keep your digestion healthy.',
      examples: [
        { name: 'Mixed Seasonal Vegetables', bnName: 'মৌসুমী সবজি' },
        { name: 'Bottle Gourd (Lau)', bnName: 'লাউ' },
        { name: 'Pumpkin (Mistikumra)', bnName: 'মিষ্টি কুমড়া' },
        { name: 'Bean & Carrot Stir-fry', bnName: 'বরবটি ও গাজর ভাজি' },
      ],
    },
  ],
  snacks: [
    {
      category: 'Healthy Fats & Protein',
      categoryBn: 'স্বাস্থ্যকর চর্বি ও প্রোটিন',
      icon: '🥜',
      nutrients: ['healthy fats', 'protein', 'fiber'],
      benefit: 'Healthy fats support your baby\'s brain development. Nuts and seeds make excellent pregnancy snacks.',
      examples: [
        { name: 'Mixed Nuts (Almonds, Walnuts)', bnName: 'মixed বাদাম (কাঠবাদাম, আখরোট)' },
        { name: 'Roasted Chickpeas (Chola)', bnName: 'রোস্টেড ছোলা' },
        { name: 'Roasted Makhana (Fox Nuts)', bnName: 'মাখানা (ভাজা)' },
        { name: 'Peanuts with Coconut', bnName: 'বাদাম ও নারিকেল' },
      ],
    },
    {
      category: 'Energy-boosting Snacks',
      categoryBn: 'শক্তি বাড়ানোর নাস্তা',
      icon: '⚡',
      nutrients: ['carbs', 'energy', 'fiber'],
      benefit: 'Small, frequent snacks help maintain blood sugar levels and prevent fatigue.',
      examples: [
        { name: 'Muri (Puffed Rice) Mix', bnName: 'মুড়ি মিক্স' },
        { name: 'Baked Sweet Potato', bnName: 'বেক করা মিষ্টি আলু' },
        { name: 'Pitha (Rice Cake) with Gur', bnName: 'পিঠা ও গুড়' },
        { name: 'Dried Fruits (Dates, Raisins)', bnName: 'শুকনো ফল (খেজুর, কিশমিশ)' },
      ],
    },
    {
      category: 'Calcium & Probiotics',
      categoryBn: 'ক্যালসিয়াম ও প্রোবায়োটিক',
      icon: '🥛',
      nutrients: ['calcium', 'probiotics', 'potassium'],
      benefit: 'Calcium builds your baby\'s bones and teeth. Probiotics aid digestion and prevent constipation.',
      examples: [
        { name: 'Yogurt (Doi) with Fruit', bnName: 'ফল সহ দই' },
        { name: 'Banana Shake with Milk', bnName: 'কলার শেক দুধ' },
        { name: 'Fruit Salad with Doi', bnName: 'ফলের সালাদ ও দই' },
        { name: 'Tok Dal (Tangy Lentil Soup)', bnName: 'টক ডাল' },
      ],
    },
  ],
  dinner: [
    {
      category: 'Light Protein',
      categoryBn: 'হালকা প্রোটিন',
      icon: '🥣',
      nutrients: ['protein', 'vitamins', 'hydration'],
      benefit: 'A light, protein-rich dinner is easier to digest and won\'t disrupt your sleep.',
      examples: [
        { name: 'Chicken Soup with Vegetables', bnName: 'চিকেন স্যুপ ও সবজি' },
        { name: 'Egg Curry (Dim Bhuna)', bnName: 'ডিম ভুনা' },
        { name: 'Fish Head Lentil Soup', bnName: 'মাছের মাথা দিয়ে ডাল' },
        { name: 'Light Chicken Curry', bnName: 'হালকা মুরগি ঝোল' },
      ],
    },
    {
      category: 'Fiber-rich Flatbread Meals',
      categoryBn: 'ফাইবারসমৃদ্ধ রুটির পদ',
      icon: '🫓',
      nutrients: ['fiber', 'carbs', 'vitamins'],
      benefit: 'Whole wheat ruti with vegetables provides fiber and steady energy without feeling heavy.',
      examples: [
        { name: 'Ruti with Dal & Shobji', bnName: 'রুটি, ডাল ও সবজি' },
        { name: 'Ruti with Vegetable Curry', bnName: 'রুটি ও সবজি তরকারি' },
        { name: 'Ruti with Egg & Shobji', bnName: 'রুটি, ডিম ও সবজি' },
      ],
    },
    {
      category: 'Calcium-rich Options',
      categoryBn: 'ক্যালসিয়ামসমৃদ্ধ পদ',
      icon: '🥛',
      nutrients: ['calcium', 'energy', 'protein'],
      benefit: 'A warm calcium-rich dinner can help you sleep better and support your baby\'s bone development.',
      examples: [
        { name: 'Vermicelli (Shemai) with Milk', bnName: 'সেমাই দুধ' },
        { name: 'Warm Milk with Gur', bnName: 'গরম দুধ ও গুড়' },
        { name: 'Fish Head Dal (Macher Matha Diye Dal)', bnName: 'মাছের মাথা দিয়ে ডাল' },
      ],
    },
    {
      category: 'Easy-to-digest Fish',
      categoryBn: 'সহজপাচ্য মাছ',
      icon: '🐠',
      nutrients: ['protein', 'calcium', 'omega3'],
      benefit: 'Soft fish like Pabda are easy to digest in the evening while providing essential nutrients.',
      examples: [
        { name: 'Pabda Macher Jhal', bnName: 'পাবদা মাছের ঝাল' },
        { name: 'Shorshe Ilish (moderate)', bnName: 'সরষে ইলিশ (পরিমিত)' },
        { name: 'Chingri Malai Curry (light)', bnName: 'চিংড়ি মালাই কারি (হালকা)' },
      ],
    },
  ],
  avoid: [
    { name: 'Raw or Undercooked Fish/Meat', bnName: 'কাঁচা বা আধা সেদ্ধ মাছ/মাংস', reason: 'Risk of toxoplasmosis and bacterial infections' },
    { name: 'Excessive Tea/Coffee', bnName: 'অতিরিক্ত চা/কফি', reason: 'Caffeine restriction — limit to 1 cup per day' },
    { name: 'Unpasteurized Milk & Dairy', bnName: 'অপাস্তুরিত দুধ ও দুগ্ধজাত', reason: 'Risk of listeria infection' },
    { name: 'Street Food with Unclear Hygiene', bnName: 'অপরিচ্ছন্ন রাস্তার খাবার', reason: 'Risk of food poisoning and gastrointestinal infections' },
    { name: 'Excessive Fried & Oily Foods', bnName: 'অতিরিক্ত ভাজা ও তেলযুক্ত খাবার', reason: 'Can worsen heartburn and cause unnecessary weight gain' },
    { name: 'Raw Papaya (Green Papaya)', bnName: 'কাঁচা পেঁপে', reason: 'Contains latex that may trigger uterine contractions' },
    { name: 'Excessively Spicy Foods', bnName: 'অতিরিক্ত মশলাদার খাবার', reason: 'Can aggravate heartburn and gastric issues during pregnancy' },
  ],
};

export const MEAL_TABS = [
  { key: 'breakfast', labelEn: 'Breakfast', labelBn: 'সকালের নাস্তা', icon: '🌅' },
  { key: 'lunch', labelEn: 'Lunch', labelBn: 'দুপুরের খাবার', icon: '☀️' },
  { key: 'snacks', labelEn: 'Evening Snacks', labelBn: 'বিকেলের নাস্তা', icon: '🌆' },
  { key: 'dinner', labelEn: 'Dinner', labelBn: 'রাতের খাবার', icon: '🌙' },
];
