export const PROVIDERS = [
  {
    id: 'dmch',
    name: 'Dhaka Medical College Hospital',
    bnName: 'ঢাকা মেডিকেল কলেজ হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'low',
    address: 'Secretariat Road, Dhaka 1000',
    phone: '01914111111',
    lat: 23.7266, lng: 90.3967,
  },
  {
    id: 'bsmmu',
    name: 'BSMMU (Bangabandhu Sheikh Mujib Medical University)',
    bnName: 'বঙ্গবন্ধু শেখ মুজিব মেডিকেল বিশ্ববিদ্যালয়',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'low',
    address: 'Shahbag, Dhaka 1000',
    phone: '01914111111',
    lat: 23.7381, lng: 90.3961,
  },
  {
    id: 'square',
    name: 'Square Hospital',
    bnName: 'স্কয়ার হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'high',
    address: '18/F West Panthapath, Dhaka 1205',
    phone: '01914111111',
    lat: 23.7481, lng: 90.3900,
  },
  {
    id: 'apollo',
    name: 'Evercare Hospital (formerly Apollo)',
    bnName: 'এভারকেয়ার হাসপাতাল (সাবেক অ্যাপোলো)',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'high',
    address: 'Plot 81, Block E, Bashundhara R/A, Dhaka 1229',
    phone: '01914111111',
    lat: 23.8125, lng: 90.4234,
  },
  {
    id: 'united',
    name: 'United Hospital',
    bnName: 'ইউনাইটেড হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'high',
    address: 'Plot 15, Road 71, Gulshan 2, Dhaka 1212',
    phone: '01914111111',
    lat: 23.7895, lng: 90.4080,
  },
  {
    id: 'icddrb',
    name: 'ICDDR,B (Maternal & Child Health)',
    bnName: 'আইসিডিডিআরবি (মাতৃ ও শিশু স্বাস্থ্য)',
    services: ['normal', 'maternity'],
    cost: 'medium',
    address: '68 Shaheed Tajuddin Ahmed Sarani, Mohakhali, Dhaka 1212',
    phone: '01914111111',
    lat: 23.7767, lng: 90.4012,
  },
  {
    id: 'pg_hospital',
    name: 'Sir Salimullah Medical College Hospital',
    bnName: 'স্যার সলিমুল্লাহ মেডিকেল কলেজ হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'low',
    address: 'Mitford Road, Dhaka 1100',
    phone: '01914111111',
    lat: 23.7089, lng: 90.4089,
  },
  {
    id: 'cmh',
    name: 'Combined Military Hospital (CMH)',
    bnName: 'সম্মিলিত সামরিক হাসপাতাল (সিএমএইচ)',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'low',
    address: 'Dhaka Cantonment, Dhaka 1206',
    phone: '01914111111',
    lat: 23.8153, lng: 90.3956,
  },
  {
    id: 'labaid',
    name: 'Labaid Specialized Hospital',
    bnName: 'ল্যাবএইড স্পেশালাইজড হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'high',
    address: 'House 6, Road 4, Dhanmondi, Dhaka 1205',
    phone: '01914111111',
    lat: 23.7465, lng: 90.3759,
  },
  {
    id: 'ibn_sina',
    name: 'Ibn Sina Medical College Hospital',
    bnName: 'ইবনে সিনা মেডিকেল কলেজ হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'medium',
    address: '1/B, Kallyanpur Main Road, Dhaka 1207',
    phone: '01914111111',
    lat: 23.7638, lng: 90.3552,
  },
  {
    id: 'shsmc',
    name: 'Shaheed Suhrawardy Medical College Hospital',
    bnName: 'শহীদ সোহরাওয়ার্দী মেডিকেল কলেজ হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'low',
    address: 'Sher-E-Bangla Nagor, Dhaka 1207',
    phone: '01914111111',
    lat: 23.7597, lng: 90.3774,
  },
  {
    id: 'popular',
    name: 'Popular Medical Center & Hospital',
    bnName: 'পপুলার মেডিকেল সেন্টার ও হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'medium',
    address: 'House 4, Road 7, Dhanmondi, Dhaka 1205',
    phone: '01914111111',
    lat: 23.7411, lng: 90.3714,
  },
  {
    id: 'birdem',
    name: 'BIRDEM General Hospital',
    bnName: 'বিরডেম জেনারেল হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'low',
    address: '122 Kazi Nazrul Islam Ave, Shahbag, Dhaka 1000',
    phone: '01914111111',
    lat: 23.7387, lng: 90.3936,
  },
  {
    id: 'ad_din',
    name: 'Ad-Din Hospital',
    bnName: 'আদ-দ্বীন হাসপাতাল',
    services: ['normal', 'maternity'],
    cost: 'low',
    address: '2 Bara Maghbazar, Dhaka 1217',
    phone: '01914111111',
    lat: 23.7519, lng: 90.4047,
  },
  {
    id: 'city_hospital',
    name: 'Dhaka City Hospital',
    bnName: 'ঢাকা সিটি হাসপাতাল',
    services: ['normal', 'csection', 'maternity', 'emergency'],
    cost: 'medium',
    address: '24 Bir Uttam ANM Nuruzzaman Sarak, Dhaka 1205',
    phone: '01914111111',
    lat: 23.7435, lng: 90.3883,
  },
];

export const SERVICE_OPTIONS = [
  { key: 'normal', labelEn: 'Normal Delivery', labelBn: 'সাধারণ প্রসব' },
  { key: 'csection', labelEn: 'C-Section', labelBn: 'সিজারিয়ান' },
  { key: 'maternity', labelEn: 'Maternity Care', labelBn: 'মাতৃত্ব সেবা' },
  { key: 'emergency', labelEn: 'Emergency Care', labelBn: 'জরুরি সেবা' },
];

export const COST_BANDS = [
  { key: 'low', labelEn: 'Low (Government)', labelBn: 'কম (সরকারি)' },
  { key: 'medium', labelEn: 'Medium (Private)', labelBn: 'মাঝারি (বেসরকারি)' },
  { key: 'high', labelEn: 'High (Premium)', labelBn: 'উচ্চ (প্রিমিয়াম)' },
];
